version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
  target-branch: "main"
  commit-message:
    prefix: "[bot][main]"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
  target-branch: "8.13.x"
  commit-message:
    prefix: "[bot][8.13.x]"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"