= OptaWeb Vehicle Routing

image:https://travis-ci.com/kiegroup/optaweb-vehicle-routing.svg?branch=master[
"Build Status", link="https://travis-ci.com/kiegroup/optaweb-vehicle-routing"]

Web application for solving the https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html[Vehicle Routing Problem]
using https://www.optaplanner.org/[OptaPlanner].

== Running the Application

First, clone this repository and `cd` into it.

Frontend and backend are built and run independently. Open two terminal windows.

== Run Frontend

. Install `npm`. If you're on Fedora, you can do this by running:
+
[source,shell]
----
sudo dnf install npm
----

. Install dependencies:
+
[source,shell]
----
cd optaweb-vehicle-routing-frontend
npm install
----

. Run frontend:
+
[source,shell]
----
npm start
----

. Open http://localhost:3000/

[TIP]
.Prevent `npm start` from launching your default browser
====
If you don't want `npm start` to open a new browser tab each time you run it,
export an environment variable `BROWSER=none`.

You can use `.env.local` file to make this preference permanent.
To do that, run

[source,shell]
----
echo BROWSER=none >> .env.local
----
====

== Run Backend

JDK 8 is the only system prerequisite. To install OpenJDK 8 on Fedora, run:

[source,shell]
----
sudo dnf install java-1.8.0-openjdk-devel
----

. Download OpenStreetMap data for Belgium from Geofabrik:
.. Open http://download.geofabrik.de/europe/belgium.html.
.. Download the OSM file http://download.geofabrik.de/europe/belgium-latest.osm.pbf[belgium-latest.osm.pbf].
.. Save it to `optaweb-vehicle-routing/optaweb-vehicle-routing-backend/local/openstreetmap/belgium-latest.osm.pbf`.

. Build backend:
+
[source,shell]
----
cd optaweb-vehicle-routing-backend
./mvnw install
----

. Run backend:
+
[source,shell]
----
java -jar target/optaweb-vehicle-routing-backend-*.jar
----

See
xref:optaweb-vehicle-routing-backend/README.adoc#development-guide[Backend Development Guide]
to learn how to run backend during development.

[TIP]
.Use a different OSM file
====
If you want to try a different region than Belgium, download an OSM file from Geofabrik
and use an argument when starting the backend to change the data file:

[source,shell]
----
java -jar target/optaweb-vehicle-routing-backend-*.jar --app.routing.osmfile=massachusetts-latest.osm.pbf
----
====

[CAUTION]
.Using large OSM files
====
For best user experience it is recommended to use smaller regions like individual European or US states.
Using OSM files larger than 1 GB will require significant RAM size
and take a lot of time (up to several hours) for the initial processing.
====
