= OptaWeb Vehicle Routing

image:https://travis-ci.com/kiegroup/optaweb-vehicle-routing.svg?branch=master[
"Build Status", link="https://travis-ci.com/kiegroup/optaweb-vehicle-routing"]

image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=alert_status[
"Quality Gate Status", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]
image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=reliability_rating[
"Reliability Rating", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]
image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=security_rating[
"Security Rating", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]
image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=sqale_rating[
"Maintainability Rating", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]
image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=ncloc[
"Lines of Code", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]
image:https://sonarcloud.io/api/project_badges/measure?project=org.optaweb:vehicle-routing&metric=coverage[
"Coverage", link="https://sonarcloud.io/dashboard?id=org.optaweb:vehicle-routing"]

Web application for solving the https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html[Vehicle Routing Problem]
using https://www.optaplanner.org/[OptaPlanner].

== Running the Application

First, clone this repository and `cd` into it.

Frontend and backend are built and run independently. Open two terminal windows.

== Run Frontend

. Install `npm`. If you're on Fedora, you can do this by running:
+
[source,shell]
----
sudo dnf install npm
----

. Install dependencies:
+
[source,shell]
----
cd optaweb-vehicle-routing-frontend
npm install
----

. Run frontend:
+
[source,shell]
----
npm start
----

. Open http://localhost:3000/

[TIP]
.Prevent `npm start` from launching your default browser
====
If you don't want `npm start` to open a new browser tab each time you run it,
export an environment variable `BROWSER=none`.

You can use `.env.local` file to make this preference permanent.
To do that, run

[source,shell]
----
echo BROWSER=none >> .env.local
----
====

== Run Backend

JDK 8 is the only system prerequisite. To install OpenJDK 8 on Fedora, run:

[source,shell]
----
sudo dnf install java-1.8.0-openjdk-devel
----

. Download OpenStreetMap data for Belgium from Geofabrik:
.. Open http://download.geofabrik.de/europe/belgium.html.
.. Download the OSM file http://download.geofabrik.de/europe/belgium-latest.osm.pbf[belgium-latest.osm.pbf].
.. Save it to `optaweb-vehicle-routing/optaweb-vehicle-routing-backend/local/openstreetmap/belgium-latest.osm.pbf`.

. Build backend:
+
[source,shell]
----
cd optaweb-vehicle-routing-backend
./mvnw install
----

. Run backend:
+
[source,shell]
----
java -jar target/optaweb-vehicle-routing-backend-*.jar
----

See
xref:optaweb-vehicle-routing-backend/README.adoc#development-guide[Backend Development Guide]
to learn how to run backend during development.

== Configuring the Working Region

If you want to try a different region than Belgium, download an OSM file from
http://download.geofabrik.de/[Geofabrik]
and select it with `app.routing.osm-file` property when starting the backend.

Don't forget to use `app.region.country-codes` property to override geosearch results constraint.

There is currently only one out-of-the-box data set for Belgium
so the *Load demo* button won't work with other regions.

[source,shell]
----
java -jar target/optaweb-vehicle-routing-backend-*.jar \
--app.routing.osm-file=massachusetts-latest.osm.pbf \
--app.region.country-codes=US
----

[CAUTION]
.Using large OSM files
====
For best user experience it is recommended to use smaller regions like individual European or US states.
Using OSM files larger than 1 GB will require significant RAM size
and take a lot of time (up to several hours) for the initial processing.
====

== Creating Custom Data Sets

There is a built-in demo data set consisting of a several large Belgian cities.
If you want to have more demos offered by the *Load demo* dropdown,
you can prepare your own data sets.
To do that, follow these steps:

. Add a depot and a set of visits by clicking on the map or using geosearch.
. Click *Export* and save the file in `optaweb-vehicle-routing-backend/local/data` directory.
. Edit the YAML file and choose a unique name for the data set.
. Restart the backend.

After you restart the backend, files in the `data` directory will be made available
in the *Load demo* dropdown.
