:projectKey: org.optaweb.vehiclerouting:optaweb-vehicle-routing
:sonarBadge: image:https://sonarcloud.io/api/project_badges/measure?project={projectKey}
:sonarLink: link="https://sonarcloud.io/dashboard?id={projectKey}"

= OptaWeb Vehicle Routing

image:https://travis-ci.com/kiegroup/optaweb-vehicle-routing.svg?branch=master[
"Build Status", link="https://travis-ci.com/kiegroup/optaweb-vehicle-routing"]
image:https://img.shields.io/badge/stackoverflow-ask_question-orange.svg?logo=stackoverflow[
"Ask question on Stack Overflow", link="https://stackoverflow.com/questions/tagged/optaplanner"]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg?logo=zulip[
"Join Zulip Chat", link="https://kie.zulipchat.com/#narrow/stream/232679-optaplanner"]

{sonarBadge}&metric=alert_status["Quality Gate Status", {sonarLink}]
{sonarBadge}&metric=reliability_rating["Reliability Rating", {sonarLink}]
{sonarBadge}&metric=security_rating["Security Rating", {sonarLink}]
{sonarBadge}&metric=sqale_rating["Maintainability Rating", {sonarLink}]
{sonarBadge}&metric=ncloc["Lines of Code", {sonarLink}]
{sonarBadge}&metric=coverage["Coverage", {sonarLink}]

Web application for solving the https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html[Vehicle Routing Problem]
using https://www.optaplanner.org/[OptaPlanner].

== Run the application using a Bash script

If you're on Linux or macOS, you can use `runLocally.sh` to start the application on your computer.

* Use `runLocally.sh` with no arguments to run with the defaults.
This will download an OSM file needed to work with the built-in data set.

* Use `runLocally.sh -i` for the interactive mode.
In this mode you can choose from downloaded OSM files or download more OSM files.

* Use `runLocally.sh <REGION>` to run with the selected region.

See the
xref:optaweb-vehicle-routing-docs/src/main/asciidoc/run-locally.adoc[documentation]
to learn more about the `runLocally.sh` script.

== Run the application in development mode

First, clone this repository and `cd` into it.

Frontend and backend are built and run independently. Open two terminal windows. Start the backend first, and then, when the backend is ready, start the frontend.

=== Running the backend

See
xref:optaweb-vehicle-routing-backend/README.adoc#_development_guide[Backend Development Guide]
to learn how to run backend during development.

==== Configuring the working region

If you want to try a different region than Belgium, download an OSM file from
http://download.geofabrik.de/[Geofabrik]
and select it with `app.routing.osm-file` property when starting the backend.

Don't forget to use `app.region.country-codes` property to override geosearch results constraint.

There is currently only one out-of-the-box data set for Belgium so the *Load demo* button won't work with other regions.

[source,shell]
----
java -jar target/optaweb-vehicle-routing-backend-*.jar \
--app.routing.osm-file=massachusetts-latest.osm.pbf \
--app.region.country-codes=US
----

[CAUTION]
.Using large OSM files
====
For best user experience, use smaller regions like individual European or US states.
Using OSM files larger than 1 GB will require significant RAM size
and take a lot of time (up to several hours) for the initial processing.
====

=== Running the frontend

. Install `npm`. If you're on Fedora, you can do this by running:
+
[source,shell]
----
sudo dnf install npm
----

. Install dependencies:
+
[source,shell]
----
cd optaweb-vehicle-routing-frontend
npm install
----

. Run frontend:
+
[source,shell]
----
npm start
----

. Open http://localhost:3000/ in a web browser. By default, the `npm start` command attempts to open this URL in your default browser.

[TIP]
.Prevent `npm start` from launching your default browser
====
If you don't want `npm start` to open a new browser tab each time you run it,
export an environment variable `BROWSER=none`.

You can use `.env.local` file to make this preference permanent.
To do that, run

[source,shell]
----
echo BROWSER=none >> .env.local
----
====
