= Development guide

== Project structure

The project is a multi-module Maven project.

.Module dependency tree diagram
image::modules.dot.svg[align="center"]

At the bottom of the module tree there are the backend and frontend modules,
which contain the application source code.

The standalone module is an assembly module that combines backend and frontend into a single executable JAR file.

The distribution module represents the final assembly step.
It takes the standalone application and the documentation and wraps them in an archive that is easy to distribute.

=== Backend

Backend module contains a server-side application that uses OptaPlanner to *optimize vehicle routes*.
It is a CPU-intensive computation, that must avoid any I/O operations in order to perform to its full potential.
Because one of the chief objectives is to minimize the travel cost, be it time or distance,
we need to keep the travel cost information in RAM memory.
While solving, OptaPlanner needs to know the travel cost between every pair of locations that the user has entered.
This information is stored in a structure called the _distance matrix_.

When a new location is entered, we calculate the travel cost between the new location and every other location that has been entered so far, and store it in the distance matrix.
The travel cost calculation is performed by a routing engine called https://github.com/graphhopper/graphhopper[GraphHopper].

Finally, the backend module implements additional functionality like

- persistence,
- WebSocket connection for the frontend,
- data set loading, export and import.

=== Frontend

=== Standalone

=== Documentation

=== Distribution

== Building the project

Run `./mvnw install` or `mvn install`.

== Developing backend

////
- OptaPlanner, GraphHopper
- Spring Boot
- Configuration (`application.properties`, `application-*.properties`)
- Package structure
- DevTools
- Docker
////

== Developing frontend

////
- PatternFly, Leaflet
- Npm, React, Redux, TypeScript, ESLint, Cypress, `ncu`
- Chrome, plugins
- Docker
////
