= Development guide

== Project structure

The project is a multi-module Maven project.

.Module dependency tree diagram
image::modules.dot.svg[align="center"]

At the bottom of the module tree there are the backend and frontend modules,
which contain the application source code.

The standalone module is an assembly module that combines backend and frontend into a single executable JAR file.

The distribution module represents the final assembly step.
It takes the standalone application and the documentation and wraps them in an archive that is easy to distribute.

== Developing OptaWeb Vehicle Routing

Backend and frontend are separate projects that can be built and deployed separately.
In fact, they are written in completely different languages and built with different tools.
Both projects have tools that provide a modern developer experience with fast turn-around between code changes and the running application.

In the next sections you will learn how to run both backend and frontend projects in development mode.

[[backend]]
== Backend

////
- OptaPlanner, GraphHopper
- Spring Boot
- Configuration (`application.properties`, `application-*.properties`)
- Package structure
- DevTools
- Docker
////

Backend module contains a server-side application that uses OptaPlanner to *optimize vehicle routes*.
Optimization is a CPU-intensive computation, that must avoid any I/O operations in order to perform to its full potential.
Because one of the chief objectives is to minimize the travel cost, be it time or distance,
we need to keep the travel cost information in RAM memory.
While solving, OptaPlanner needs to know the travel cost between every pair of locations entered by the user.
This information is stored in a structure called the _distance matrix_.

When a new location is entered, we calculate the travel cost between the new location and every other location that has been entered so far, and store the travel cost in the distance matrix.
The travel cost calculation is performed by a routing engine called https://github.com/graphhopper/graphhopper[GraphHopper].

Finally, the backend module implements additional, supporting functionality like

- persistence,
- WebSocket connection for the frontend,
- data set loading, export and import.

In the next sections you will learn how to configure and run backend in development mode.
To learn more about the backend code architecture, see <<appendix-backend-architecture#_backend_architecture>>.

=== Running backend using Spring Boot Maven plugin

.Prerequisites
. Java 8 or higher is <<quickstart#_install_java_8_or_higher,installed>>.
. Data directory is set up.
. An OSM file is downloaded.
// TODO application-local.properties

You can accomplish prerequisites 2 and 3 either by using the <<run-locally#run-locally-sh,run script>> or by performing them <<run-noscript#run-noscript,manually>>.

.Procedure
To run backend in development mode, enter:

[source,shell]
----
mvn spring-boot:run
----

=== Automatic restart

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart[Automatic restart]
is provided by Spring Boot DevTools and only works when the backend is running using <<_running_backend_using_spring_boot_maven_plugin, Spring Boot Maven Plugin>>.
It scans files on the classpath, so you only need to recompile your changes to trigger application restart.
No IDE configuration is needed.

If your IDE has a compile-on-save feature (Eclipse, NetBeans), you just need to save the files that have changed since last compilation.

IntelliJ IDEA saves changes automatically and you need to use either Recompile action, which recompiles the file in active tab, or Build Project action which recompiles all changes.
See https://www.jetbrains.com/help/idea/compiling-applications.html[Compile and build applications with IntelliJ IDEA].

=== Running backend from IntelliJ IDEA

. Run `org.optaweb.vehiclerouting.OptaWebVehicleRoutingApplication` from Project window.
This will create a Run Configuration that you will edit in the next step.
A failure on the first run is expected due to wrong working directory.

. Select menu:Run[Edit Configurations...] and then select menu:Spring Boot[OptaWebVehicleRoutingApplication].

. Set *Program arguments* to `--spring.profiles.active=local` to activate the Spring profile called `local`.
This will make the application use configuration from `application-local.properties`.

. Change *Working directory* to the backend module (`optaweb-vehicle-routing-backend`).

. Optionally, set *On Update action* to *Hot swap classes and update trigger file if failed*.
This will allow you to use the Update action to quickly restart the application.
+
See https://blog.jetbrains.com/idea/2018/04/spring-and-spring-boot-in-intellij-idea-2018-1/[Spring and Spring Boot in IntelliJ IDEA 2018.1]
for more details.

=== Configuration

There are multiple ways how to set configuration properties.
When running locally, you'll probably want to use one of these:

* Set it using `application.properties` (you'll find it under `/src/main/resources/`).
* A command line argument when running the packaged application (e.g. `java -jar optaweb-vehicle-routing-backend.jar --app.my-property=value1`).
* An environment variable when running the application with `spring-boot:run`.
+
For example: `app_my_property=value1 ./mvnw spring-boot:run` if the property name is `app.my-property` (this requires
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding[relaxed binding]
which only works if the property is defined using `@ConfigurationProperties`).

[NOTE]
It's not possible to set properties simply via `-D` when running the application using Spring Boot Maven plugin (`./mvnw spring-boot:run -Dmy-property`).
Any system properties that should be set by the plugin to the forked Java process in which the application runs need to be specified using `systemPropertiesVariables`
https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-system-properties.html[plugin configuration].

You can learn more about configuring a Spring Boot application
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Spring Boot Externalized Configuration].

[TIP]
Use `src/main/resources/application-local.properties` to store your personal configuration without affecting Git working tree.

See the complete list of <<appendix-backend-config#_backend_configuration_properties>>.

See also the complete list of
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[
common application properties] available in Spring Boot.

=== Logging

OptaWeb uses SLF4J API and Logback as the logging framework.
Spring Environment allows to configure most logging aspects including levels, patterns and log files in the same way as any other <<_configuration>> (most often using `application.properties` or arguments `--property=value`).
See
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-custom-log-levels[
Spring Boot Logging] documentation for more information.

For example, you may use:

- `logging.level.org.optaweb.vehiclerouting=debug` to enable debug level for the backend code,
- `logging.level.org.optaplanner.core=warn` to reduce OptaPlanner logging,
- `logging.level.org.springframework.web.socket=trace` to access more details when investigating problems with WebSocket connection.

== Frontend

////
- PatternFly, Leaflet
- Npm, React, Redux, TypeScript, ESLint, Cypress, `ncu`
- Chrome, plugins
- Docker
////

== Building the project

Run `./mvnw install` or `mvn install`.
