= Development guide

== Project structure

The project is a multi-module Maven project.

.Module dependency tree diagram
image::modules.dot.svg[align="center"]

At the bottom of the module tree there are the backend and frontend modules,
which contain the application source code.

The standalone module is an assembly module that combines backend and frontend into a single executable JAR file.

The distribution module represents the final assembly step.
It takes the standalone application and the documentation and wraps them in an archive that is easy to distribute.

== Backend

Backend module contains a server-side application that uses OptaPlanner to *optimize vehicle routes*.
Optimization is a CPU-intensive computation, that must avoid any I/O operations in order to perform to its full potential.
Because one of the chief objectives is to minimize the travel cost, be it time or distance,
we need to keep the travel cost information in RAM memory.
While solving, OptaPlanner needs to know the travel cost between every pair of locations entered by the user.
This information is stored in a structure called the _distance matrix_.

When a new location is entered, we calculate the travel cost between the new location and every other location that has been entered so far, and store the travel cost in the distance matrix.
The travel cost calculation is performed by a routing engine called https://github.com/graphhopper/graphhopper[GraphHopper].

Finally, the backend module implements additional, supporting functionality like

- persistence,
- WebSocket connection for the frontend,
- data set loading, export and import.

=== Backend architecture

Domain model and use cases are essential for the application.
We put domain model at the center of the architecture and surround it by the application layer, that embeds use cases.
Functions such as route optimization, distance calculation, persistence, and network communication are considered implementation details
and are placed at the outermost layer of the architecture.

.Diagram of application layers
image::backend-layers.svg[align="center"]

==== Code organization

The backend code is organized in three layers outlined above.

[literal]
....
org.optaweb.vehiclerouting
├── domain
├── plugin          # Infrastructure layer
│   ├── persistence
│   ├── planner
│   ├── routing
│   └── websocket
└── service         # Application layer
    ├── demo
    ├── distance
    ├── location
    ├── region
    ├── reload
    ├── route
    └── vehicle
....

The `service` package contains the application layer, implementing use cases.
The `plugin` package contains the infrastructure layer.

Code in each layer is further organized by function.
That means each service or plugin has its own package.

==== Dependency rules

Compile-time dependencies are only allowed to point from outer layers towards the center.
Following this rule helps to keep domain model independent of underlying frameworks and other implementation details,
and model the behavior of business entities more precisely.
With presentation and persistence being pushed out to the periphery, it is easier to test the behavior of business entities and use cases.

The domain has no dependencies.

Services only depend on the domain.
If a service needs to send a result (e.g. to a database or web socket), it uses an output boundary interface.
Its implementation is injected by the IoC container.

Plugins depend on services in two ways.
Firstly, they invoke services based on events such as a user input or a route update coming from the optimization engine.
Services are injected into plugins, which moves the burden of their construction and dependency resolution to the IoC container.
Secondly, plugins implement services' output boundary interfaces to handle use case results, e.g. persisting changes to database, sending response to web UI.

==== Domain package

The `domain` package contains "business objects" that model the domain of this project,
for example Visit, Depot, Location, Vehicle.
These objects are strictly business-oriented and must not be influenced
by any tools and frameworks (e.g. ORM, marshalling formats etc.).

==== Services package

The `service` package contains classes that implement "use cases".
A use case is for example adding new location, changing vehicle capacity or finding coordinates for an address.
The business rules that govern use cases are expressed using the domain objects.

Use cases often need to interact with outer layers, such as persistence, web and optimization.
To keep the code loosely coupled, the interaction with the outer layers is expressed in terms of interfaces.
Their implementations are provided by Spring IoC container at runtime.

==== Plugins package

The `plugin` package contains infrastructure functions such as optimization, persistence, routing and network.

=== Configuration

There are multiple ways how to set configuration properties.
When running locally, you'll probably want to use one of these:

* Set it using `application.properties` (you'll find it under `/src/main/resources/`).
* A command line argument when running the packaged application (e.g. `java -jar optaweb-vehicle-routing-backend.jar --app.my-property=value1`).
* An environment variable when running the application with `spring-boot:run`.
+
For example: `app_my_property=value1 ./mvnw spring-boot:run` if the property name is `app.my-property` (this requires
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding[relaxed binding]
which only works if the property is defined using `@ConfigurationProperties`).

[NOTE]
It's not possible to set properties simply via `-D` when running the application using Spring Boot Maven plugin (`./mvnw spring-boot:run -Dmy-property`).
Any system properties that should be set by the plugin to the forked Java process in which the application runs need to be specified using `systemPropertiesVariables`
https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-system-properties.html[plugin configuration].

You can learn more about configuring a Spring Boot application
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Spring Boot Externalized Configuration].

[TIP]
Use `src/main/resources/application-local.properties` to store your personal configuration without affecting Git working tree.

See also the complete list of
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[
common application properties] available in Spring Boot.

[cols="m,d,a,d",options="header"]
|===

|Property
|Type
|Example
|Description

|app.persistence.h2-dir
|Relative or absolute path
|/home/user/{data-dir-name}/db
|The directory used by H2 to store the database file.
Defaults to `local/db`.

|app.region.country-codes
|List of https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2[ISO 3166-1 alpha-2] country codes
|`US`, `GB,IE`, `DE,AT,CH`, may be empty
|Restricts geosearch results.

|app.routing.engine
|Enumeration
|`air`, `graphhopper`
|Routing engine implementation.
Defaults to `graphhopper`.

|app.routing.gh-dir
|Relative or absolute path
|/home/user/{data-dir-name}/graphhopper
|The directory used by GraphHopper to store road network graphs.
Defaults to `local/graphhopper`.

|app.routing.osm-dir
|Relative or absolute path
|/home/user/{data-dir-name}/openstreetmap
|The directory that contains OSM files.
Defaults to `local/openstreetmap`.

|app.routing.osm-file
|File name
|belgium-latest.osm.pbf
|Name of the OSM file that should be loaded by GraphHopper.
The file must be placed under `app.routing.osm-dir`.

|optaplanner.solver.termination.spent-limit
|java.time.Duration
|* 1m
* 150s
* P2dT21h (PnDTnHnMn.nS)
|How long the solver should run after a location change occurs.

|server.address
|IP address or hostname
|10.0.0.123, my-vrp.geo-1.openshiftapps.com
|Network address to which the server should bind.

|server.port
|Port number
|4000, 8081
|Server HTTP port.

|===

=== Logging

OptaWeb uses SLF4J API and Logback as the logging framework.
Spring Environment allows to configure most logging aspects including levels, patterns and log files in the same way as any other <<_configuration>> (most often using `application.properties` or arguments `--property=value`).
See
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-custom-log-levels[
Spring Boot Logging] documentation for more information.

For example, you may use:

- `logging.level.org.optaweb.vehiclerouting=debug` to enable debug level for the backend code,
- `logging.level.org.optaplanner.core=warn` to reduce OptaPlanner logging,
- `logging.level.org.springframework.web.socket=trace` to access more details when investigating problems with WebSocket connection.

=== Running backend from IntelliJ IDEA

1. Run `org.optaweb.vehiclerouting.OptaWebVehicleRoutingApplication` from Project window.
This will create a Run Configuration that you will edit in the next step.
A failure on the first run is expected due to wrong working directory.

2. Select menu:Run[Edit Configurations...] and then select menu:Spring Boot[OptaWebVehicleRoutingApplication].

3. Change *Working directory* to the backend module (`optaweb-vehicle-routing-backend`).

4. Optionally, set *On Update action* to *Hot swap classes and update trigger file if failed*.
This will allow you to use the Update action to quickly restart the application.
+
See https://blog.jetbrains.com/idea/2018/04/spring-and-spring-boot-in-intellij-idea-2018-1/[Spring and Spring Boot in IntelliJ IDEA 2018.1]
for more details.

=== Automatic restart

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart[Automatic restart]
is provided by Spring Boot DevTools.
It scans files on the classpath, so you only need to recompile your changes to trigger application restart.
No IDE configuration is needed.

If your IDE has a compile-on-save feature (Eclipse, NetBeans), you just need to save the files that have changed since last compilation.

IntelliJ IDEA saves changes automatically and you need to use either Recompile action, which recompiles the file in active tab, or Build Project action which recompiles all changes.
See https://www.jetbrains.com/help/idea/compiling-applications.html[Compile and build applications with IntelliJ IDEA].

== Frontend

== Standalone

== Documentation

== Distribution

== Building the project

Run `./mvnw install` or `mvn install`.

== Developing backend

////
- OptaPlanner, GraphHopper
- Spring Boot
- Configuration (`application.properties`, `application-*.properties`)
- Package structure
- DevTools
- Docker
////

== Developing frontend

////
- PatternFly, Leaflet
- Npm, React, Redux, TypeScript, ESLint, Cypress, `ncu`
- Chrome, plugins
- Docker
////
