== Introduction

=== What is OptaWeb Vehicle Routing?

Transporting various types of cargo is the goal or a vital part of many businesses.
The business's goal is not only to deliver a piece of cargo from the loading point to its destination but also use its vehicle fleet in the most efficient way.
This type of optimization problem is referred to as the https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html[vehicle routing problem] (VRP) and has many variations.

https://www.optaplanner.org/[OptaPlanner] can solve many of these vehicle routing variations and has a few examples proving that.
That makes developers’ lives easier because they can focus on modeling the business rules and requirements instead of learning https://en.wikipedia.org/wiki/Constraint_programming[constraint programming] theory.
With *OptaWeb Vehicle Routing*, we're making a step further and building a reference implementation that also gives answers to questions like
"Where do I get the distances and travel times?",
"How do I visualize the solution on a map?" or
"How do I build an application that runs in the cloud?".
