[#run-openshift]
= Run on OpenShift

Linux and macOS users can use a Bash script called `runOnOpenShift.sh` to install OptaWeb Vehicle Routing on OpenShift.

== Running on a local OpenShift cluster

Use https://developers.redhat.com/products/codeready-containers[Red Hat CodeReady Containers]
to easily set up a single-node OpenShift 4 cluster on your local computer.

.Prerequisites
You have successfully built the project with Maven.

.Procedure
1. To install CRC, follow the https://code-ready.github.io/crc/[Getting Started Guide].

2. When the cluster has started,

a. add oc command-line interface to your `$PATH`:
+
[source,shell]
----
eval $(crc oc-env)
----

b. log in as "developer".
+
[source,shell]
----
oc login -u developer -p developer https://api.crc.testing:6443
----

3. Create a new project
+
[source,subs="quotes"]
----
oc new-project _project_name_
----

4. Run the script:
+
[source,subs="quotes"]
----
./runOnOpenShift.sh _osm_file_name_ _country_code_list_ _osm_file_download_url_
----
+
or

+
[source,shell]
----
./runOnOpenShift.sh --help
----
+
to see more details about how to use the script.

=== Updating the deployed application with local changes

==== Backend

Change the source code and build the backend module with Maven.
Then start OpenShift build:

[source,shell]
----
cd optaweb-vehicle-routing-backend
oc start-build backend --from-dir=. --follow
----

==== Frontend

Change the source code and build the frontend module with npm.
Then start OpenShift build:

[source,shell]
----
cd optaweb-vehicle-routing-frontend
oc start-build frontend --from-dir=docker --follow
----
