:david-project: https://david-dm.org/kiegroup/optaweb-vehicle-routing
:david-path: path=optaweb-vehicle-routing-frontend
:david-deps: {david-project}/status.svg?{david-path}
:david-devDeps: {david-project}/dev-status.svg?{david-path}
:david-link: {david-project}?{david-path}

[[optaweb-vehicle-routing-frontend]]
= OptaWeb Vehicle Routing front end

image:{david-deps}["dependencies Status",link="{david-link}"]
image:{david-devDeps}["devDependencies Status",link="{david-link}&type=dev"]

[[available-scripts]]
== Available scripts

In the project directory, you can run:

[[npm-start]]
=== `npm start`

Runs the app in the development mode.
Open http://localhost:3000 to view it in the browser.

The page will reload if you make edits.
You will also see any lint errors in the console.

[[npm-test]]
=== `npm test`

Launches the test runner in the interactive watch mode.
See the section about https://create-react-app.dev/docs/running-tests/[running tests] for more information.

[[npm-run-lint]]
=== `npm run lint`

Check the whole `src/` directory for linter errors.
Some IDEs are difficult to be configured to be 100% compliant with the project linter configuration.
Use `npm run lint:fix` to resolve the edge cases that your IDE cannot handle.

[[npm-run-build]]
=== `npm run build`

Builds the app for production to the `build` folder.
It correctly bundles React in production mode and optimizes the build for the best performance.

See the section about https://create-react-app.dev/docs/deployment/[deployment] for more information.

[[browserslist-support]]
== Browserslist support

Developers set versions list in queries like `last 2 version` to be free from updating versions manually.
Browserslist will use http://caniuse.com/[Can I Use] data for this queries.

Check the project current browser query on
https://browserl.ist/?q=%3E0.2%25%2C+not+dead%2C+not+ie%3C%3D11%2Cnot+op_mini+all[browserl.ist]
or by running `npx browserslist`.

Example:

[source,json]
----
{
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
----

[[learn-more]]
== Learn more

To learn React, check out the https://reactjs.org/[React documentation].

This project was bootstrapped with
https://github.com/facebook/create-react-app[Create React App].

Learn more on
https://github.com/browserslist/browserslist#readme[Browserslist].
