const SOLUTION_UPDATES_DATA = 'SOLUTION_UPDATES_DATA';
const DELETE_LOCATION = 'DELETE_LOCATION';
const ADD_LOCATION = 'ADD_LOCATION';
const ADD_DEMO_LOCATION = 'ADD_DEMO_LOCATION';
const WS_CONNECT = 'WS_CONNECT';
const WS_CONNECT_SUCCESS = 'WS_CONNECT_SUCCESS';
const WS_CONNECT_FAILURE = 'WS_CONNECT_FAILURE';


export default {
  SOLUTION_UPDATES_DATA,
  DELETE_LOCATION,
  ADD_LOCATION,
  ADD_DEMO_LOCATION,
  WS_CONNECT,
  WS_CONNECT_SUCCESS,
  WS_CONNECT_FAILURE,
};
